### ISSUE TITLE
Latex Resume

### ISSUE THREAD

**Issue by EhsanKai** [MuhammedBuyukkinaci/Data-Scientist-LaTeX-Resume-with-Photo#2]
Hi Muhammed,
I really liked your work. Would you please send me this resume?
Thank you so much

**Comment by MuhammedBuyukkinaci** [comment]
Hi,

You can navigate [here](https://github.com/MuhammedBuyukkinaci/Data-Scientist-LaTeX-Resume-with-Photo) and download the project as a zip file via clicking Code button.

![Screenshot from 2023-11-04 18-24-58](https://github.com/MuhammedBuyukkinaci/Data-Scientist-LaTeX-Resume-with-Photo/assets/33747602/d72a39ad-7ad3-4c75-9a4f-4ad0ae8d2282)
